// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://docvfyakpyatqnlwwayz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvY3ZmeWFrcHlhdHFubHd3YXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjY0MDEsImV4cCI6MjA2NjU0MjQwMX0.XCwCcq6jSVpR_b1XrpJMTNrOovjr7_ZnWn5y-5N5aNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);